version: "3"
services:
  reverseproxy:
    build:
      context: ../../udagram-reverseproxy
    image: superrynz/reverseproxy
  backend_user:
    build:
      context: ../../udagram-api-user
    image: superrynz/udagram-api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed
    image: superrynz/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-frontend
    image: superrynz/udagram-frontend